FROM nginx:latest


COPY index.html /usr/share/nginx/html

#COPY nginx.conf /etc/nginx/nginx.conf

VOLUME [ "/data" ]

WORKDIR /data

#COPY volume/file1.txt .
#COPY volume/file2.txt .

EXPOSE 80

LABEL description="Ajout des volumes"